# Generated by Django 2.1.5 on 2019-02-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190226_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('Can mark returned', 'Set book as returned'),)},
        ),
    ]
